[tool.poetry]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]


[tool.poetry.dependencies]
python = ">=3.10"
sqlalchemy = "^2.0.36"
pandas = "^2.2.3"

